/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Kari (https://sketchfab.com/keetos349)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/goku-rigged-animated-3ed060df9f4a4134963e61f3ca95ee7d
Title: Goku (Rigged & Animated)
*/

import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations, useFBX } from "@react-three/drei";

export default function Goku(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "/models/Goku/goku_rigged__animated.glb"
  );
  const fbx = useFBX("/models/Goku/boxing.fbx");
  const { actions } = useAnimations(animations, group);

  console.log(actions.Idle);
  useEffect(() => {
    if (actions) {
      actions["Idle"].play(); // Replace "AnimationName" with the actual name of the animation
    }
  }, [actions]);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group
          name="Sketchfab_model"
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.04}
        >
          <group
            name="be5965086adc4214ac9c0c747c30be52fbx"
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.025}
          >
            <group name="Object_2">
              <group name="RootNode">
                <group name="Object_4">
                  <primitive object={nodes._rootJoint} />
                  <skinnedMesh
                    name="Object_7"
                    geometry={nodes.Object_7.geometry}
                    material={materials["tex1.png"]}
                    skeleton={nodes.Object_7.skeleton}
                  />
                  <skinnedMesh
                    name="Object_8"
                    geometry={nodes.Object_8.geometry}
                    material={materials["tex2.png"]}
                    skeleton={nodes.Object_8.skeleton}
                  />
                  <skinnedMesh
                    name="Object_10"
                    geometry={nodes.Object_10.geometry}
                    material={materials["tex4.png"]}
                    skeleton={nodes.Object_10.skeleton}
                  />
                  <skinnedMesh
                    name="Object_12"
                    geometry={nodes.Object_12.geometry}
                    material={materials["tex1.png"]}
                    skeleton={nodes.Object_12.skeleton}
                  />
                  <skinnedMesh
                    name="Object_13"
                    geometry={nodes.Object_13.geometry}
                    material={materials["tex2.png"]}
                    skeleton={nodes.Object_13.skeleton}
                  />
                  <skinnedMesh
                    name="Object_15"
                    geometry={nodes.Object_15.geometry}
                    material={materials["tex3.png"]}
                    skeleton={nodes.Object_15.skeleton}
                  />
                  <skinnedMesh
                    name="Object_16"
                    geometry={nodes.Object_16.geometry}
                    material={materials["tex4.png"]}
                    skeleton={nodes.Object_16.skeleton}
                  />
                  <skinnedMesh
                    name="Object_18"
                    geometry={nodes.Object_18.geometry}
                    material={materials["face1.png"]}
                    skeleton={nodes.Object_18.skeleton}
                  />
                  <group name="Object_6" scale={39.37} />
                  <group name="Object_9" scale={39.37} />
                  <group name="Object_11" scale={39.37} />
                  <group name="Object_14" scale={39.37} />
                  <group name="Object_17" scale={39.37} />
                  <group name="Right_Hand" scale={39.37} />
                  <group name="Hair" scale={39.37} />
                  <group name="Left_Hand" scale={39.37} />
                  <group name="Body" scale={39.37} />
                  <group name="Face" scale={39.37} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/Goku/goku_rigged__animated.glb");
