/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: MajdyModels (https://sketchfab.com/MG990)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/iphone-16-pro-max-41a071ae12794b668502f58d1e0fd1a3
Title: iPhone 16 Pro Max
*/

import React, { useRef } from "react";
import { Float, useGLTF } from "@react-three/drei";

export default function iphone(props) {
  const { nodes, materials } = useGLTF("./models/iphone_16_pro_max.glb");
  return (
    <Float>
      <group {...props} dispose={null}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group>
              <group
                position={[7.94022751, 61.85214615, 6.7665906]}
                rotation={[-Math.PI / 2, Math.PI / 2, 0]}
                scale={3.77685356}
              >
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Circle010_black002_0.geometry}
                  material={materials["black.002"]}
                />
              </group>
              <group
                position={[7.8248806, 71.85492706, 25.40520096]}
                rotation={[-Math.PI / 2, Math.PI / 2, 0]}
                scale={1.70086062}
              >
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Circle011_black002_0.geometry}
                  material={materials["black.002"]}
                />
              </group>
              <group
                position={[7.9241581, 51.98717117, 25.28789902]}
                rotation={[-Math.PI / 2, Math.PI / 2, 0]}
                scale={2.42372823}
              >
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Circle012_black002_0.geometry}
                  material={materials["black.002"]}
                />
              </group>
              <group
                position={[-4.60435677, 78.55760956, 7.24876833]}
                rotation={[Math.PI / 2, -Math.PI / 2, 0]}
                scale={1.6431464}
              >
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Circle013_black002_0.geometry}
                  material={materials["black.002"]}
                />
              </group>
              <group
                position={[-0.32841489, 2.26033926, 0.19882657]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={100}
              >
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube014_black002_0.geometry}
                  material={materials["black.002"]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube014_basecolor001_0.geometry}
                  material={materials["basecolor.001"]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube014_metalframe002_0.geometry}
                  material={materials["metalframe.002"]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube014_metaL001_0.geometry}
                  material={materials["metaL.001"]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube014_glass002_0.geometry}
                  material={materials["glass.002"]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube014_apple_logo001_0.geometry}
                  material={materials["apple_logo.001"]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube014_screen001_0.geometry}
                  material={materials["screen.001"]}
                />
              </group>
              <group
                position={[0.03407672, -79.37578583, -0.69571996]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={100}
              >
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube015_Material001_0.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group
                position={[-1.41231346, 78.52540588, -2.20901036]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={100}
              >
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube016_black002_0.geometry}
                  material={materials["black.002"]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube016_glass002_0.geometry}
                  material={materials["glass.002"]}
                />
              </group>
              <group
                position={[-0.39498135, -6.00093937, -38.30291367]}
                rotation={[-Math.PI / 2, -4e-8, Math.PI / 2]}
                scale={1.48238444}
              >
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube017_metalframe002_0.geometry}
                  material={materials["metalframe.002"]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube017_black002_0.geometry}
                  material={materials["black.002"]}
                />
              </group>
              <group
                position={[5.38218689, 71.83042908, 25.41187668]}
                rotation={[-Math.PI / 2, Math.PI / 2, 0]}
                scale={[8.28784943, 8.28784943, 2.59469581]}
              >
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cylinder018_metalframe002_0.geometry}
                  material={materials["metalframe.002"]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cylinder018_black002_0.geometry}
                  material={materials["black.002"]}
                />
              </group>
              <group
                position={[5.38218689, 51.98535919, 25.27607346]}
                rotation={[-Math.PI / 2, Math.PI / 2, 0]}
                scale={[8.28784943, 8.28784943, 2.59469581]}
              >
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cylinder019_metalframe002_0.geometry}
                  material={materials["metalframe.002"]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cylinder019_black002_0.geometry}
                  material={materials["black.002"]}
                />
              </group>
              <group
                position={[5.38218689, 61.85264587, 6.76887941]}
                rotation={[-Math.PI / 2, Math.PI / 2, 0]}
                scale={[8.28784943, 8.28784943, 2.59469581]}
              >
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cylinder020_metalframe002_0.geometry}
                  material={materials["metalframe.002"]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cylinder020_black002_0.geometry}
                  material={materials["black.002"]}
                />
              </group>
              <group
                position={[2.33514977, 75.92111969, 6.84021425]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={100}
              >
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cylinder021_metalframe002_0.geometry}
                  material={materials["metalframe.002"]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cylinder021_Material_0.geometry}
                  material={materials.Material}
                />
              </group>
              <group
                position={[0.84822845, 47.8237381, 6.80321169]}
                rotation={[-Math.PI / 2, Math.PI / 2, 0]}
                scale={3.34622478}
              >
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cylinder022_black002_0.geometry}
                  material={materials["black.002"]}
                />
              </group>
              <group
                position={[5.38218689, 71.83042908, 25.41187668]}
                rotation={[-Math.PI / 2, Math.PI / 2, 0]}
                scale={[8.28784943, 8.28784943, 2.59469581]}
              >
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.len11001_glass002_0.geometry}
                  material={materials["glass.002"]}
                />
              </group>
              <group
                position={[5.38218689, 61.85264587, 6.76887941]}
                rotation={[-Math.PI / 2, Math.PI / 2, 0]}
                scale={[8.28784943, 8.28784943, 2.59469581]}
              >
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.len22001_glass002_0.geometry}
                  material={materials["glass.002"]}
                />
              </group>
              <group
                position={[5.38218689, 51.98535919, 25.27607346]}
                rotation={[-Math.PI / 2, Math.PI / 2, 0]}
                scale={[8.28784943, 8.28784943, 2.59469581]}
              >
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.len33001_glass002_0.geometry}
                  material={materials["glass.002"]}
                />
              </group>
              <group
                position={[-0.19118115, -80.59909058, -0.72089696]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={100}
              >
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object003_gray001_0.geometry}
                  material={materials["gray.001"]}
                />
              </group>
              <group
                position={[5.84119034, 63.50154877, 15.6775322]}
                rotation={[-Math.PI / 2, Math.PI / 2, 0]}
                scale={19.93716431}
              >
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Plane011_glass002_0.geometry}
                  material={materials["glass.002"]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Plane011_basecolor001_0.geometry}
                  material={materials["basecolor.001"]}
                />
              </group>
              <group
                position={[5.3669281, 51.21384811, 0.79010463]}
                rotation={[-Math.PI / 4, Math.PI / 2, 0]}
                scale={[0.3942624, 0.3942624, 0.39426243]}
              >
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Plane012_metalframe002_0.geometry}
                  material={materials["metalframe.002"]}
                />
              </group>
              <group
                position={[-0.21859929, -81.44258881, 11.40659714]}
                rotation={[Math.PI / 2, -2e-7, -2.3561945]}
                scale={1.05762446}
              >
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Plane013_metaL001_0.geometry}
                  material={materials["metaL.001"]}
                />
              </group>
              <group
                position={[-0.21859929, -81.44258881, -20.01754379]}
                rotation={[Math.PI / 2, -2e-7, -2.3561945]}
                scale={1.05762446}
              >
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Plane014_metaL001_0.geometry}
                  material={materials["metaL.001"]}
                />
              </group>
              <group
                position={[7.2966404, 71.86511993, 25.40043259]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={[0.55676281, 1.25475156, 1.25475156]}
              >
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Sphere010_lensinglass_0.geometry}
                  material={materials.lensinglass}
                />
              </group>
              <group
                position={[7.33731461, 51.99529648, 25.29114151]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={[0.95200443, 2.14549017, 2.14549017]}
              >
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Sphere011_lensinglass_0.geometry}
                  material={materials.lensinglass}
                />
              </group>
              <group
                position={[7.37479401, 61.86976624, 6.74828005]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={[0.64083946, 2.91789532, 2.91789532]}
              >
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Sphere012_lensinglass_0.geometry}
                  material={materials.lensinglass}
                />
              </group>
              <group
                position={[-4.09404564, 78.56746674, 7.2535367]}
                rotation={[-Math.PI / 2, 0, -Math.PI]}
                scale={[0.53787041, 1.21217477, 1.21217477]}
              >
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Sphere013_lensinglass_0.geometry}
                  material={materials.lensinglass}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </Float>
  );
}

useGLTF.preload("./models/iphone_16_pro_max.glb");
